[changelog]
header = "# Changelog\n"
body = """
{% if version %}\
## {{ version }} — {{ timestamp | date(format="%d. %B %Y") }}
{% else %}\
## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}\
{{ commit.message | upper_first }}\
{% if commit.breaking %} — **BREAKING CHANGE**{% endif %}

{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat",     group = "Features" },
  { message = "^fix",      group = "Bug Fixes" },
  { message = "^perf",     group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^style",    group = "Styling" },
  { message = "^docs",     group = "Documentation" },
  { message = "^chore",    skip = true },
  { message = "^ci",       skip = true },
  { message = "^build",    skip = true },
]
protect_breaking_commits = false
filter_commits = true
tag_pattern = "v[0-9]*"
sort_commits = "oldest"
